name: Fetch Roblox Group Members

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run fetch script
      run: npm start

    - name: Commit and push updated JSON
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add groupMembers.json
        git commit -m "Update group members [bot]" || echo "No changes"
        git push
